name: CI/CD para dockerrizar aplicacao Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  teste:
    runs-on: ubuntu-latest

    steps:
    - name: baixando o código para o servidor
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalando as dependencias
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pytest

    - name: Executandos os testes
      run: |
        pytest

  build-e-push:
    needs: teste
    runs-on: ubuntu-latest

    steps:
    - name: baixando o código para o servidor
      uses: actions/checkout@v3


    - name: Logando no dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKENACCESS }}

    - name: Build e push no dockerhub
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker/DockerFile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/rancher:testeeres-latest 

    - name: Image digest
      run: echo ${{ steps.build-e-push.outputs.digest }}